golang: Upgrade golang14 to latest source-only release so we can bootstrap it
Otherwise it started to fail this way:

[2017-02-22 11:49:22,982] INFO     --- FAIL: TestLoadFixed (0.00s)
[2017-02-22 11:49:22,982] INFO          time_test.go:929: Now().In(loc).Zone() = "-01", -3600, want "GMT+1", -3600
[2017-02-22 11:49:22,983] INFO     FAIL
[2017-02-22 11:49:22,983] INFO     FAIL time    2.380s

See https://github.com/golang/go/issues/16352#issuecomment-255835099 and around
for details.