Fix libsanitizer for older GCC in newer machines.
When compiling older GCC versions in newer machines, libsanitizer
does not compile, showing a error: `multiple definition of
'enum fsconfig_command'` (e.g.
https://github.com/llvm/llvm-project/issues/56421).
This is because starting from Glibc 2.36, it is not possible to include
both "linux/fs.h" and "sys/mount.h".

We can apply a patch, similar to the one in
https://reviews.llvm.org/D129471 , but with the extension and lines
changed to match the file. This is also similar to the upstream fix.

See merge request nexedi/slapos!1579