Fix invalid uses of `computer_partition_root_path`
The variable `computer_partition_root_path` is now a `pathlib.Path`
object, so we should use the `/` operator instead of the `+` operator.
This should fix the following error:

```python
Traceback (most recent call last):
  File "/srv/slapgrid/slappart41/t/eoc/soft/194a5e26f7fbb6223f692d18ea91980a/parts/slapos-repository/software/erp5-zope2/test/test/test_erp5.py", line 263, in test_test_runner_configuration_json_file
    self.computer_partition_root_path + "/../*/bin/runUnitTest.real")
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

We try to do the minimal changes for the tests to pass, not a whole
refactoring like in !1662. We can discuss later how to further unify the
`erp5` and `erp5-zope2` branches and reduce code duplication.