software/cloudooo: fix typo in section name
this the download to be installed without a checksum, so buildout's
download utility makes a hardlink when installing software from a git
checkout as software URL and cause an error like this when updating:

    shutil.SameFileError: '/srv/slapgrid/slappart41/t/czt/soft/471e28359c5c64d85cdd314861220c57/parts/slapos-repository/software/cloudooo/instance-cloudooo-output-schema.json' and '/srv/slapgrid/slappart41/t/czt/i/0/tmp/soft/8c6e7e6efc37012e98af9127da0525c7/parts/json-schema/instance-cloudooo-output-schema.json' are the same file

Co-authored-by: Xavier Thompson <xavier.thompson@nexedi.com>