component/trafficserver: build without libcap
We don't want to build against system library that might or might not be
present on the host.

This also cause SR test to fail with:

    RuntimeError: /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_manager uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_crashlog uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_server uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_ctl uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_logstats uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_via uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_cop uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_layout uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/bin/traffic_logcat uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/lib/libtsutil.so.7.1.6 uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/lib/libtsmgmt.so.7.1.6 uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2                                        /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/lib/libtsmgmt.so.7 uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/lib/libtsmgmt.so uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/lib/libtsutil.so.7 uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2
  /data/slappart11_testnode/cqg/inst/test0-0/tmp/soft/c4089a16e2c60e6d38833e611ff37fcd/parts/trafficserver7/lib/libtsutil.so uses system library /lib/x86_64-linux-gnu/libcap.so.2 for libcap.so.2