ERP5: really fix build of [slapos-deps-eggs]
This fixes the following random failures:

While:
  Installing slapos-deps-eggs.
  Getting distribution for 'ZODB3==3.10.5+SlapOSPatched001'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  ...
  File "zc/buildout/easy_install.py", line 968, in _get_dist
    shutil.copytree(dist.location, newloc)
  File "shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '.../eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg'