wendelin.core: tests: Pin ZopeUndo
ZEO[test] requires ZopeUndo, but we now never pin that anywhere in e.g. stack/slapos.cfg .
Previously it was working without explicit pinning because Zope2, contrary to Zope4, pins ZopeUndo to 2.12.0.

Build of test-zodb5.cfg was failing as

    Installing wendelin.core-python.
    While:
      Installing wendelin.core-python.
      Base installation request: 'wendelin.core[test]', 'pygolang[pyx.build]', 'neoppod[tests]', 'ZEO[test]'
        Requirement of ZEO[test]==5.4.0: zope.testrunner
        Requirement of ZEO[test]==5.4.0: zdaemon
        Requirement of ZEO[test]==5.4.0: msgpack<1
        Requirement of ZEO[test]==5.4.0: mock
        Requirement of ZEO[test]==5.4.0: transaction
        Requirement of ZEO[test]==5.4.0: manuel
        Requirement of ZEO[test]==5.4.0: zope.testing
        Requirement of ZEO[test]==5.4.0: ZopeUndo
        Requirement of ZEO[test]==5.4.0: ZODB>=5.5.1
        Requirement of ZEO[test]==5.4.0: ZConfig
        Requirement of ZEO[test]==5.4.0: trollius
        Requirement of ZEO[test]==5.4.0: futures
        Requirement of ZEO[test]==5.4.0: zope.interface
        Requirement of ZEO[test]==5.4.0: zdaemon
        Requirement of ZEO[test]==5.4.0: ZConfig
        Requirement of ZEO[test]==5.4.0: zc.lockfile
        Requirement of ZEO[test]==5.4.0: persistent>=4.1.0
        Requirement of ZEO[test]==5.4.0: transaction>=2.0.3
        Requirement of ZEO[test]==5.4.0: six
        Requirement of ZEO[test]==5.4.0: ZODB>=5.1.1
        Requirement of neoppod[tests]==1.12.0: neoppod[admin,client,ctl,master,storage-importer,storage-mysqldb,storage-pymysql,storage-sqlite]
        Requirement of neoppod[tests]==1.12.0: psutil>=2
        Requirement of neoppod[tests]==1.12.0: zope.testing
        Requirement of neoppod[tests]==1.12.0: coverage
        Requirement of neoppod[tests]==1.12.0: python-dateutil
        Requirement of neoppod[tests]==1.12.0: msgpack>=0.5.6
        Requirement of pygolang[pyx.build]==0.1: wheel
        Requirement of pygolang[pyx.build]==0.1: setuptools_dso>=1.7
        Requirement of pygolang[pyx.build]==0.1: setuptools
        Requirement of pygolang[pyx.build]==0.1: cython
        Requirement of pygolang[pyx.build]==0.1: Importing
        Requirement of pygolang[pyx.build]==0.1: decorator
        Requirement of pygolang[pyx.build]==0.1: six
        Requirement of pygolang[pyx.build]==0.1: gevent
        Requirement of wendelin.core[test]: ZEO
        Requirement of wendelin.core[test]: neoppod
        Requirement of wendelin.core[test]: scipy
        Requirement of wendelin.core[test]: pytest
        Requirement of wendelin.core[test]: psutil
        Requirement of wendelin.core[test]: six
        Requirement of wendelin.core[test]: pygolang>=0.1
        Requirement of wendelin.core[test]: zodbtools>=0.0.0.dev8
        Requirement of wendelin.core[test]: ZODB>=4
        Requirement of wendelin.core[test]: numpy
        Requirement of zope.testrunner: zope.interface
        Requirement of zope.testrunner: zope.exceptions
        Requirement of zope.testrunner: six
        Requirement of zope.testrunner: setuptools
        Requirement of zdaemon: setuptools
        Requirement of zdaemon: ZConfig
        Requirement of mock: funcsigs>=1
        Requirement of mock: six
        Requirement of transaction: zope.interface
        Requirement of manuel: six
        Requirement of manuel: setuptools
        Requirement of zope.testing: setuptools
      Getting distribution for 'ZopeUndo'.
    Error: Picked: ZopeUndo = 6.0

-> pin ZopeUndo to 5.0 - the last version that supports both py2 and py3.