software/gitlab: fix ethon gem failing to load libcurl
ethon https://github.com/typhoeus/ethon try to load libcurl and fail. It seems not
possible to configure bundler to build ethon with libcurl.

rake aborted!
LoadError: Could not open library 'libcurl': libcurl: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so': libcurl.so: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so.4': libcurl.so.4: cannot open shared object file: No such file or directory
/srv/slapgrid/slappart57/t/esj/i/0/tmp/soft/089f161175935a31b4b66a6a4eebb97e/parts/bundler-4gitlab/lib/ruby/gems/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib'
/srv/slapgrid/slappart57/t/esj/i/0/tmp/soft/089f161175935a31b4b66a6a4eebb97e/parts/bundler-4gitlab/lib/ruby/gems/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
/srv/slapgrid/slappart57/t/esj/i/0/tmp/soft/089f161175935a31b4b66a6a4eebb97e/parts/bundler-4gitlab/lib/ruby/gems/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
/srv/slapgrid/slappart57/t/esj/i/0/tmp/soft/089f161175935a31b4b66a6a4eebb97e/parts/bundler-4gitlab/lib/ruby/gems/gems/ethon-0.15.0/lib/ethon/curls/settings.rb:10:in `<module:Curl>'
/srv/slapgrid/slappart57/t/esj/i/0/tmp/soft/089f161175935a31b4b66a6a4eebb97e/parts/bundler-4gitlab/lib/ruby/gems/gems/ethon-0.15.0/lib/ethon/curls/settings.rb:3:in `<module:Ethon>'
/srv/slapgrid/slappart57/t/esj/i/0/tmp/soft/089f161175935a31b4b66a6a4eebb97e/parts/bundler-4gitlab/lib/ruby/gems/gems/ethon-0.15.0/lib/ethon/curls/settings.rb:2:in `<top (required)>