pygolang: Pin zodbpickle in tests
Starting from https://lab.nexedi.com/nexedi/pygolang/-/commit/95fd2889
pygolang needs zodbpickle for tests. So without pinning zodbpickle
testnodes starrted to error with

    Installing gpython-interpreter.
    While:
      Installing gpython-interpreter.
      Base installation request: 'pygolang[all_test]'
        Requirement of pygolang[all_test]: py; python_version >= "3" and extra == "all_test"
        Requirement of pygolang[all_test]: zodbpickle; extra == "all-test"
        Requirement of pygolang[all_test]: wheel; extra == "all-test"
        Requirement of pygolang[all_test]: setuptools-dso>=2.8; extra == "all-test"
        Requirement of pygolang[all_test]: setuptools; extra == "all-test"
        Requirement of pygolang[all_test]: pytest; extra == "all-test"
        Requirement of pygolang[all_test]: numpy; extra == "all-test"
        Requirement of pygolang[all_test]: ipython; extra == "all-test"
        Requirement of pygolang[all_test]: cython<3; extra == "all-test"
        Requirement of pygolang[all_test]: geventmp; python_version >= "3" and platform_system != "Windows"
        Requirement of pygolang[all_test]: setuptools>=60.2; python_version >= "3"
        Requirement of pygolang[all_test]: setuptools-dso>=2.8
        Requirement of pygolang[all_test]: decorator
        Requirement of pygolang[all_test]: six
        Requirement of pygolang[all_test]: gevent
      Getting distribution for 'zodbpickle; extra == "all-test"'.
    Error: Picked: zodbpickle = 4.2

    The `zodbpickle` egg does not have a version pin and `allow-picked-versions = false`.

    To resolve this, add

        zodbpickle = 4.2

    to the [versions] section,

    OR set `allow-picked-versions = true`.

/cc @jerome