software/ors-amarisoft: enb/ors: test: Use valid frequencies
So far in the unit tests we were only generating enb.cfg without semantically
processing as running lteenb is not possible on testnodes due to licensing
restrictions. That allowed to use arbitrary numbers, even invalid, for
frequencies without hitting an error.

However in the next patch we are going to start handling frequencies ourselves,
and invalid frequencies will lead to instantiation failures like

    ... in dl2ul(dl_earfcn)
    KeyError: 'no band that corresponds to DL EARFCN=325320'

Avoid that by switching to valid LTE and NR frequency numbers in the test.