component/tesseract: declare a minimal gcc version
With gcc 6.3.0 we see build failures:

    error: no matching function for call to 'tesseract::STRING::STRING()'

According to https://github.com/tesseract-ocr/tesseract/issues/3210#issuecomment-774599019
minimal gcc version is version 7.

This probably started to break since d6dd75df3 (component/ghostscript:
version up 9.54.0, 2021-05-25) and 5f616dd7d (component/tesseract: version
up 4.1.1, 2021-05-20).

This gcc is needed for both tesseract and ghostscript, because ghostscript
build again its embedded copy of tesseract.