rapid-cdn: fix failing test
logrotate test for the rapid-cdn SR have been failing for quite some
time because of a squid.log file created (and henceforth rotated) on
any slave instance of the CDN:

```
Traceback (most recent call last):
    self.assertEqual(
AssertionError: Items in the second set but not the first:
'squid.log_10.0.160.212.20240306.23h57m09s-20240307.00h00m02s.old.xz'
```

Since we do not want to test this file in that specific test, this
commit instead loosely check the content of the rotated files
directory.
In other words, the test now checks for the presence of the two
files to be tested, but avoid failing if other files exist.

This goes in line with the two following lines of that same test,
loosely checking for file absence instead of an empty directory.

/cc @tomo @luke
/approved-by @luke
/reviewed-on !1541