component/fluentd: fix failing install updating ruby version
- updates component/fluentd ruby version to 2.7 to fix :

  ERROR:  Error installing fluentd:
	msgpack requires Ruby version >= 2.4.

  encountered while supplying software/fluentd in a SlapOS Webrunner.

- removes outdated gem arguments '--no-ri --no-rdoc'
  by default `rubygemsrecipe` uses '--no-document' (see https://lab.nexedi.com/nexedi/rubygemsrecipe/blob/7fd5bd1aa3ef701931e394d1422a6c86cb852cfd/rubygems.py#L206)

- splits `gem-options` arguments to fit the README example (see https://lab.nexedi.com/nexedi/rubygemsrecipe/blob/7fd5bd1aa3ef701931e394d1422a6c86cb852cfd/README.rst#L50)

- adds minimal test to check fluentd SR instanciation