software/rapic-cdn/test: fix dependency for beautifulsoup4
https://pypi.org/project/bs4/0.0.2/

"This is a dummy package designed to prevent namesquatting on PyPI.
You should install beautifulsoup4 instead."

because this package uses hatchling, this fail installing in buildout:

ModuleNotFoundError: No module named 'hatchling'