slaprunner: keep old recipe eggs otherwise instance can't be upgraded
As we have runners with a section deployed using
collective.recipe.shelloutput, if collective.recipe.shelloutput isn't in
the SR folder anymore thisi section can't be uninstalled (as the
uninstall method is defined in the egg).

The output of buildout for this error was :

While:
  Installing.
  Uninstalling runner-sshkeys-publickey-fingerprint-shelloutput.
  Installing recipe collective.recipe.shelloutput.
  Getting distribution for 'collective.recipe.shelloutput'.
Error: We don't have a distribution for collective.recipe.shelloutput
and can't install one in offline (no-install) mode.
While:
  Installing switch_softwaretype.