software/kvm: fix netconfig.sh and ipv6_config.sh scripts
When adding a route to an interface not up yet, "ip route" command fails
with:

Error: Device for nexthop is not up.

So we need to up the device before adding the routes.