build-rina: fix build of hellorina SR in test-rina
While:
  Installing lxml-python.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/mnt/buildout/eggs/zc.buildout-2.5.2+slapos005-py2.7.egg/zc/buildout/buildout.py", line 2211, in main
    getattr(buildout, command)(args)
  File "/mnt/buildout/eggs/zc.buildout-2.5.2+slapos005-py2.7.egg/zc/buildout/buildout.py", line 637, in install
    self._install_parts(install_args)
  File "/mnt/buildout/eggs/zc.buildout-2.5.2+slapos005-py2.7.egg/zc/buildout/buildout.py", line 806, in _install_parts
    installed_files = self[part]._call(recipe.install)
  File "/mnt/buildout/eggs/zc.buildout-2.5.2+slapos005-py2.7.egg/zc/buildout/buildout.py", line 1579, in _call
    return f()
  File "/home/slapos/software/eggs/zc.recipe.egg-1.3.2.post5-py2.7.egg/zc/recipe/egg/custom.py", line 49, in install
    return self._install()
  File "/home/slapos/software/eggs/zc.recipe.egg-1.3.2.post5-py2.7.egg/zc/recipe/egg/custom.py", line 161, in _install
    newest=self.newest, patch_dict=patch_dict)
  File "/mnt/buildout/eggs/zc.buildout-2.5.2+slapos005-py2.7.egg/zc/buildout/easy_install.py", line 1061, in build
    assert executable == sys.executable, (executable, sys.executable)
AssertionError: ('/home/slapos/software/parts/python2.7/bin/python2.7', '/usr/bin/python')