software/theia: fix instance error when instance is not ASCII
b'💥' is a SyntaxError in python.

Instead, switch to accessing options from option variable and apply
this to other options from this part.

This fixes this issue:

    While:
      Installing switch-softwaretype.
      Installing favicon.ico.

    An internal error occurred due to a bug in either zc.buildout or in a
    recipe being used:
    Traceback (most recent call last):
      File "zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 2360, in main
        getattr(buildout, command)(args)
      File "zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 640, in install
        self._install_parts(install_args)
      File "zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 820, in _install_parts
        installed_files = self[part]._call(recipe.install)
      File "zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 1668, in _call
        return f()
      File "slapos.cookbook-1.0.244-py3.7.egg/slapos/recipe/switch_softwaretype.py", line 108, in install
        sub_buildout.install([])
      File "zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 640, in install
        self._install_parts(install_args)
      File "zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 820, in _install_parts
        installed_files = self[part]._call(recipe.install)
      File "zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 1668, in _call
        return f()
      File "slapos.recipe.build-0.54-py3.7.egg/slapos/recipe/build/__init__.py", line 268, in install
        return self._shared.install(self.__install)
      File "slapos.recipe.build-0.54-py3.7.egg/slapos/recipe/__init__.py", line 150, in install
        install()
      File "slapos.recipe.build-0.54-py3.7.egg/slapos/recipe/build/__init__.py", line 278, in __install
        self._exec(self._install)
      File "slapos.recipe.build-0.54-py3.7.egg/slapos/recipe/build/__init__.py", line 261, in _exec
        code = compile(script, self.name, 'exec')
      File "favicon.ico", line 6
    SyntaxError: bytes can only contain ASCII literal characters.