component/qt5-qmake: Fix build failure on systems with libxcb
On systems where libxcb is installed but
xcb-util-wm libraries are not available via
the system package manager, building
qt5-qmake fails [1]. By explicitly deactivating
xcb during the build, we can fix this issue.

[1] ...
checking for xcb...
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o xcb.o xcb.cpp
xcb.cpp: In function ‘int main(int, char**)’:
xcb.cpp:39:23: warning: unused variable ‘t’ [-Wunused-variable]
   39 |     xcb_connection_t *t = xcb_connect("", &primaryScreen);
      |                       ^
g++ -Wl,-O1 -o xcb xcb.o   -lxcb
xcb enabled.
checking for xcb-syslibs...
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o xcb.o xcb.cpp
xcb.cpp:38:10: fatal error: xcb/xcb_icccm.h: No such file or directory
   38 | #include <xcb/xcb_icccm.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:183: xcb.o] Error 1
xcb-syslibs disabled.
The test for linking against libxcb and support libraries failed!
 You might need to install dependency packages, or pass -qt-xcb.
 See src/plugins/platforms/xcb/README.