stack/erp5-zope2: Backport changes from MR !1640
Backport the changes of the ZEO configuration to Zope 2, to prevent
the following bug during `slapos node instance`:

```python
Traceback (most recent call last):
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 2664, in main
    getattr(buildout, command)(args)
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 855, in install
    self._install_parts(install_args)
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1026, in _install_parts
    installed_files = self[part]._call(recipe.install)
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1948, in _call
    return f()
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/slapos.cookbook-1.0.403-py2.7.egg/slapos/recipe/switch_softwaretype.py", line 122, in install
    sub_buildout.install([])
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 855, in install
    self._install_parts(install_args)
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 906, in _install_parts
    [self[part]['recipe'] for part in install_parts]
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1610, in __getitem__
    options._initialize()
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1724, in _initialize
    self._dosub(k, v)
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1788, in _dosub
    for s in v.split('$$')])
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1883, in _sub
    options = self.buildout[section]
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1610, in __getitem__
    options._initialize()
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1736, in _initialize
    self.recipe = self.buildout.initialize(self, *_recipe(self._data))
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1581, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, self)
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1691, in _install_and_load
    req.project_name, group, entry)
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/setuptools-44.1.1-py2.7.egg/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/slapgrid/d48f33aba65193f6a61d39bdd1d67814/eggs/setuptools-44.1.1-py2.7.egg/pkg_resources/__init__.py", line 2851, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('zc.buildout', 'zeo') not found
```