Fix libarchive for CMake in newer machines.
When compiling CMake, libarchive does not compile, showing a error:
`multiple definition of 'enum fsconfig_command'` (e.g.
https://discourse.cmake.org/t/building-cmake-from-source-on-linux-fedora-37/7519/4).
This is because starting from Glibc 2.36, it is not possible to include
both "linux/fs.h" and "sys/mount.h".

We can apply a patch, similar to the one in
https://patchwork.yoctoproject.org/project/oe-core/patch/20220728143044.1696098-1-raj.khem@gmail.com/ ,
but with the filenames and lines changed to match the correct file.

Note that this error is the same in !1579 but for a different component.