Upgrade GDAL to last version with Python 2 support
The upgrade is done to version 3.2.3, as this is the last version which
still supports Python 2.

This fixes the following compilation bug:

```c
gdalwmsdataset.cpp:383:37: error: ISO C++ forbids comparison between
pointer and integer [-fpermissive]
	if(pszHttpZeroBlockCodes == '\0') {
```

Jasper is no longer a dependency, and openjpeg is used instead.

See merge request nexedi/slapos!1586.