py2-v↑: numpy, scipy, scikit-*, pandas
This commit was initially part of !1832, hoping a newer version of GCC
could be used, but in fact it changed nothing.
Replacing very old eggs with little less old ones is still useful.

Unfortunately, with numpy 1.16.x, testPylint crashes as follows:

  Traceback (most recent call last):
    File ".../parts/erp5/Products/ERP5Type/tests/testDynamicClassGeneration.py", line 2376, in testPylint
      component.checkSourceCode()
    ...
    File ".../develop-eggs/astroid-1.3.8+slapospatched002-py2.7.egg/astroid/raw_building.py", line 360, in _set_proxied
      return _CONST_PROXY[const.value.__class__]
  KeyError: <type 'numpy.ufunc'>

No idea if upgrading pylint/astroid would help;
we just don't want to do that because of !648.