ERP5: notebook 4.4.1 does not need argon2-cffi
This fixes:

  Installing jupyter.
  While:
    Installing jupyter.
    Base installation request: ...
    Getting distribution for 'argon2-cffi'.
  Error: Picked: argon2-cffi = 20.1.0

Addition of argon2-cffi in commit 7d1ea024f8e9a95e3e142e023ee6b218e118722b
was a last-minute change to fix jupyter SR.