Revert "erp5: Update tesseract to 3.04.01 because of compilation error."
This reverts commit 292be60ff42edc2ce57f2e6701ad283c18e9772b because of
a regression in tesseract > 3.02:
  https://github.com/tesseract-ocr/tesseract/issues/360#issuecomment-258775303

Related Unit Tests failures:
  * test_PDFDocument_asTextConversion (testDms.TestDocument)
  * test_MonochromeImageResize (testDms.TestDocument)
  * test_CMYKImageTextContent (testDms.TestDocument)
  => AssertionError: 'ERP5 is a free software\n\n' != 'ERPS is a free software.\n\n'

Tested versions:
  * 3.04.01 (leptnonica: 1.73): NOK
  * 3.03.03 (leptonica: 1.71): NOK
  * 3.03-rc1 (leptonica: 1.71): NOK
  * 3.02.01 (leptonica: 1.69): OK
  * 3.02 (leptonica: 1.71): OK