nextcloud: add missing monitor-htpasswd section
this seems to cause:
  Installing Computer Partition TestNextCloudParameters-0...
  Falling back to default buildout '/tmp/slaps/soft/8d7d1f38e7c55201a8be65b75e827d7b/bin/buildout'
  Uninstalling dynamic-template-lamp.
  Uninstalling slap-configuration.
  Installing slap-configuration.
  Installing dynamic-template-lamp.
  Installing switch_softwaretype.
  While:
    Installing.
    Getting section publish-connection-information.
    Initializing section publish-connection-information.
    Getting option publish-connection-information:monitor-setup-url.
    Getting section monitor-publish-parameters.
    Initializing section monitor-publish-parameters.
    Getting option monitor-publish-parameters:monitor-base-url.
    Getting section monitor-base.
    Initializing section monitor-base.
    Getting option monitor-base:base-url.
    Getting section monitor-conf-parameters.
    Initializing section monitor-conf-parameters.
    Getting option monitor-conf-parameters:base-url.
    Getting section monitor-instance-parameter.
    Initializing section monitor-instance-parameter.
    Getting option monitor-instance-parameter:monitor-base-url.
    Getting section monitor-frontend-promise.
    Initializing section monitor-frontend-promise.
    Getting option monitor-frontend-promise:config-url.
    Getting option monitor-frontend-promise:url.
    Getting section monitor-frontend.
    Initializing section monitor-frontend.
    Getting option monitor-frontend:config-url.
    Getting section monitor-httpd-conf-parameter.
    Initializing section monitor-httpd-conf-parameter.
    Getting option monitor-httpd-conf-parameter:htpasswd-file.
    Getting section httpd-monitor-htpasswd.
    Initializing section httpd-monitor-htpasswd.
    Getting option httpd-monitor-htpasswd:command.
    Getting option monitor-instance-parameter:password.
  Error: Referenced option does not exist: monitor-htpasswd passwd
  While:
    Installing switch_softwaretype