fixup! Clean up slapos.recipe.template ( f5ebda78 )
By changing jinja2-template users from overriding url= to defining
template= the original url= option was expanded, but this failed
because there is no filename=. Define a default filename to prevent
this.

This fixes errors like for example:

    While:
      Installing.
      Getting section instance.cfg.
      Initializing section instance.cfg.
      Getting option instance.cfg:url.
    Error: Referenced option does not exist: instance.cfg filename

when installing component/pygolang/test.cfg