software/kvm: keep old recipe eggs otherwise instance can't be upgraded
As we have kvm with a section deployed using
collective.recipe.shelloutput, if collective.recipe.shelloutput isn't in
the SR folder anymore this section can't be uninstalled (as the
uninstall method is defined in the egg).

The output of buildout for this error was :

Installing switch_softwaretype.
Uninstalling frontend-port.
While:
  Installing.
  Uninstalling frontend-port.
  Installing recipe collective.recipe.shelloutput.
  Getting distribution for 'collective.recipe.shelloutput'.
Error: We don't have a distribution for collective.recipe.shelloutput
and can't install one in offline (no-install) mode.

The cause was a7a36453948f55e10646a0cea94ce9eec66630a9