component/ZODB: keep running the test on python3
after slapos commit cc7f36a08 (component/defaults: use python3 by
default, 2022-08-27) this test accidentally switched to using python3.

using python3 showed an incompatibility:

   File ".nxdtest", line 23, in <module>
     TestCase('transaction',['python', '-m', 'unittest', 'discover', '-s', P(transaction)])
   File ".nxdtest", line 22, in P
     def P(path): return os.path.join(path, '..')
   File "lib/python3.8/posixpath.py", line 90, in join
     genericpath._check_arg_types('join', a, *p)
   File "lib/python3.8/genericpath.py", line 155, in _check_arg_types
     raise TypeError("Can't mix strings and bytes in path components") from None
 TypeError: Can't mix strings and bytes in path components

that we also address here by using universal_newlines to the subprocess