Revert "findutils: version up to current git master."
This reverts commit 467269a1a8d93534d31f3b1d3859218b004618da.

This is just a temporary revert until there is no failures
to build. Right now it fails with :
OSError: [Errno 2] No such file or directory