setup.py: only require enum34 for python older than 3.4
This fixes errors like:

    File "python3.6/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag