version up: gettext 1.0, m4 1.4.21
This is for gnulib commit df17f4f37ed3ca373d23ad42eae51122bdb96626,
which fixes the following error:

  error: expected identifier or '(' before '_Generic'