hugo: create tempfiles in a dedicated temporary directory
Sometimes on testnodes hugo refuses to start because:

    Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /tmp/hugo_cache/default: permission denied
    Total in 0 ms