Revert "slaprunner: ..."
This reverts commit 2cc61477e909fe48201df6fc8e599102e9f6f81f.

Now we now, without "futures" egg, gunicorn refuses to start:

    Error: class uri 'gunicorn.workers.gthread.ThreadWorker' invalid or not found:

    [Traceback (most recent call last):
      File "/srv/slapgrid/slappart14/srv/testnode/cqc/inst/test0-0/tmp/soft/8c22f5a21e7f016f38916f098ab2339b/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/util.py", line 134, in load_class
	mod = import_module('.'.join(components))
      File "/srv/slapgrid/slappart14/srv/testnode/cqc/inst/test0-0/tmp/shared/python2.7/8d8826883d34c5a7ec7a5b8c187d89c9/lib/python2.7/importlib/__init__.py", line 37, in import_module
	__import__(name)
      File "/srv/slapgrid/slappart14/srv/testnode/cqc/inst/test0-0/tmp/soft/8c22f5a21e7f016f38916f098ab2339b/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/gthread.py", line 37, in <module>
	""")
    RuntimeError:
	You need to install the 'futures' package to use this worker with this
	Python version.