software/beremiz-runtime: update beremiz.git revision
Update to current HEAD of python3 branch, as the previous version caused
errors while running tests:

    Compiling IEC Program into C code...
    0.331s
    Extracting Located Variables...
    C code generated successfully.
    PLC :
    [CC]  plc_main.c -> plc_main.o
    0.192s
    [CC]  plc_debugger.c -> plc_debugger.o
    0.101s
    Warning: /srv/slapgrid/slappart56/t/eyv/i/0/tmp/inst/BeremizRuntimeWithMd5sumTestCase-1/parts/download-plc/build/plc_debugger.c:84:8: error: unknown type name "PLC_PRG"
    Warning:    84 | extern PLC_PRG RESOURCE1__INSTANCE0;
    Warning:       |        ^~~~~~~
    Warning: /srv/slapgrid/slappart56/t/eyv/i/0/tmp/inst/BeremizRuntimeWithMd5sumTestCase-1/parts/download-plc/build/plc_debugger.c:95:14: error: unknown type name "PLC_PRG"
    Warning:    95 | extern       PLC_PRG   RESOURCE1__INSTANCE0;