deploy-test: pre-install requests
These tests are still using `python setup.py test` which installs
missing packages to their latest versions. Recently, certifi (a
requests dependency) published a new release with python3 only
syntax, so running the test now got an error installing missing
packages:

    File "parts/slapos-package/playbook/roles/standalone-shared/.eggs/certifi-2022.5.18.1-py2.7.egg/certifi/core.py", line 17
        def where() -> str:
                    ^
    SyntaxError: invalid syntax

The `playbook/roles/standalone-shared` is defined on the test suite
as instance parameters, so it seems we can not already install this
package directly from playbook/roles/standalone-shared because
test suite may define something different. For now, just install
requests. All this will have to be addressed when we change this
test to pre-install packages with slapos and use `python -m unittest`
instead of `python setup.py test`.