wendelin.core: tests: Use pygolang-compatible cython during the tests as well
Commit 9661d6cb (component/pygolang: force to use a fixed cython version
until pygolang supports cython3) adjusted pygolang and wendelin.core to
use cython2 during the build of those components. However wendelin.core
tests also require cython via pygolang[pyx.build] and for those tests no
adjustments were made.

Which still work for py2, but with upcoming py3 it will break as

    Installing wendelin.core-python.
    Version and requirements information containing cython:
      [versions] constraint on cython: 3.0.11
      Requirement of pygolang[pyx.build]: cython<3; extra == "pyx-build"
    While:
      Installing wendelin.core-python.
      Base installation request: 'wendelin.core[test]', 'pygolang[pyx.build]', 'neoppod[tests]', 'ZEO[test]'
        Requirement of ZEO[test]==6.0.0: zope.testrunner
        Requirement of ZEO[test]==6.0.0: zope.testing
        Requirement of ZEO[test]==6.0.0: transaction
        Requirement of ZEO[test]==6.0.0: msgpack
        Requirement of ZEO[test]==6.0.0: ZopeUndo
        Requirement of ZEO[test]==6.0.0: ZODB>=5.5.1
        Requirement of ZEO[test]==6.0.0: zope.interface
        Requirement of ZEO[test]==6.0.0: zdaemon
        Requirement of ZEO[test]==6.0.0: zc.lockfile
        Requirement of ZEO[test]==6.0.0: transaction>=2.0.3
        Requirement of ZEO[test]==6.0.0: persistent>=4.1.0
        Requirement of ZEO[test]==6.0.0: ZODB>=5.1.1
        Requirement of ZEO[test]==6.0.0: ZConfig
        Requirement of neoppod[tests]==1.12.0: setproctitle
        Requirement of neoppod[tests]==1.12.0: mysqlclient
        Requirement of neoppod[tests]==1.12.0: ZODB>=4.4.5
        Requirement of neoppod[tests]==1.12.0: PyMySQL
        Requirement of neoppod[tests]==1.12.0: psutil>=2
        Requirement of neoppod[tests]==1.12.0: zope.testing
        Requirement of neoppod[tests]==1.12.0: coverage
        Requirement of neoppod[tests]==1.12.0: python-dateutil
        Requirement of neoppod[tests]==1.12.0: msgpack>=0.5.6
        Requirement of pygolang[pyx.build]: wheel; extra == "pyx-build"
        Requirement of pygolang[pyx.build]: setuptools-dso>=2.8; extra == "pyx-build"
        Requirement of pygolang[pyx.build]: setuptools; extra == "pyx-build"
        Requirement of pygolang[pyx.build]: cython<3; extra == "pyx-build"
        Requirement of pygolang[pyx.build]: geventmp; python_version >= "3" and platform_system != "Windows"
        Requirement of pygolang[pyx.build]: setuptools>=60.2; python_version >= "3"
        Requirement of pygolang[pyx.build]: setuptools-dso>=2.8
        Requirement of pygolang[pyx.build]: decorator
        Requirement of pygolang[pyx.build]: six
        Requirement of pygolang[pyx.build]: gevent
        Requirement of wendelin.core[test]: ZEO[test]; extra == "test"
        Requirement of wendelin.core[test]: neoppod; extra == "test"
        Requirement of wendelin.core[test]: scipy; extra == "test"
        Requirement of wendelin.core[test]: pytest; extra == "test"
        Requirement of wendelin.core[test]: psutil
        Requirement of wendelin.core[test]: six
        Requirement of wendelin.core[test]: pygolang>=0.1
        Requirement of wendelin.core[test]: zodbtools>=0.0.0.dev8
        Requirement of wendelin.core[test]: ZODB>=4
        Requirement of wendelin.core[test]: numpy
        Requirement of zope.testrunner: zope.interface
        Requirement of zope.testrunner: zope.exceptions
        Requirement of zope.testrunner: setuptools
        Requirement of zope.testing: setuptools
        Requirement of transaction: zope.interface
        Requirement of ZopeUndo: setuptools
        Requirement of ZODB>=5.5.1: zope.interface
        Requirement of ZODB>=5.5.1: zodbpickle>=1.0.1
        Requirement of ZODB>=5.5.1: zc.lockfile
        Requirement of ZODB>=5.5.1: transaction>=2.4
        Requirement of ZODB>=5.5.1: persistent>=4.4.0
        Requirement of ZODB>=5.5.1: ZConfig
        Requirement of ZODB>=5.5.1: BTrees>=4.2.0
        Requirement of zope.interface: setuptools
        Requirement of zdaemon: setuptools
        Requirement of zdaemon: ZConfig
        Requirement of zc.lockfile: setuptools
        Requirement of persistent>=4.1.0: cffi
        Requirement of persistent>=4.1.0: zope.interface
        Requirement of python-dateutil: six>=1.5
        Requirement of setuptools-dso>=2.8; extra == "pyx-build": setuptools
    Error: The requirement ('cython<3; extra == "pyx-build"') is not allowed by your [versions] constraint (3.0.11)

-> Handle pygolang[pyx.build] in wendelin.core tests similarly to how it
was done in 9661d6cb.

/cc @jerome, @tomo, @Daetalus, @levin.zimmermann