component/ca-certificates: Enforce slapos provided python3
System wide python3 might result:

Error: attempt to use system python. Executed with: ['.../bin/python3', 'certdata2pem.py']

Thus enforce locally provided one.