publish: Access "-extends"-referenced sections during __init__
Buildout expects all needed sections to have been accessed during the
sectoin initialisation pass. It does not like having them accessed during
the "install" pass, and emits a very cryptic error:
  While:
    Installing publish.
  Error: Missing option: publish-early:__buildout_signature__