XXX Revert "component/trafficserver: build Lua plugin."
This reverts commit 50f6a55712cfa2675f46c55be0f28ac53ea614ee.

Checking if it is a source of:

RuntimeError: Software hash present in signature /srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/trafficserver/abff49577e10dd806836ced454783a03/.slapos.recipe.cmmi.signature
'__buildout_signature__': 'setuptools-44.1.1 slapos.recipe.build-0.49 slapos.recipe.cmmi-0.17 zc.buildout-2.7.1+slapos014 gcc:89f8fd681cc503c09111a56a61d37c0b libtool:aea051c0f0262e065afda3f5b5165df5 luajit:4bd4b41963fb30600da82b1e9ef984b4 make:2e92bc97c8671700554f9df292a91f5d ncurses:575ef663802eac7100604c2305d592e8 openssl:b51b8cfcd96007cc866789a265b00b91 patch:0ac3dd9661e837f7f5b7ec00230e2def pcre:6a0119fca9caf59f5dd1d1af76698112 perl:87fa6801d7e1cbe160860cb84de8d20f pkgconfig:222f1d4cc1b26d94d19902b1bfb1dd3e tcl:3964510ba4157d4c1e5e3a122323c955 xz-utils:377bc8469cc3c2a0536f3272e2af8bba zlib:8814c5249780a6955cc2d9db69e36ec3'
'configure-options': '--with-openssl=/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/openssl/98cc177187bea94018e05faf2e5a3db8\n--with-pcre=/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/pcre/985b3e8cb73ad6c1aba3a26c44b45382\n--with-ncurses=/srv/slapgrid/slappart13/srv/testnode/dfa/shared/ncurses/52ca4731167b465a97ca2faa0d2c0780\n--with-tcl=/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/tcl/334718f5f980704ed69e7148da614924/lib/\n--with-luajit=/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/soft/c4d1389fa7431ea9a1ec5e28fe32dd6a/parts/luajit\n--with-lzma=/srv/slapgrid/slappart13/srv/testnode/dfa/shared/xz-utils/78bf45ff612879c1872c409a05c614ee\n--with-zlib=/srv/slapgrid/slappart13/srv/testnode/dfa/shared/zlib/50f729c7869d762bd290da8443b3be99\n--disable-curl\n--disable-hwloc\n--enable-experimental-plugins\n--disable-posix-cap'
'environment': 'PATH=/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/libtool/42560e9264b3e8227547653fe635d690/bin:/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/make/0479956b107add38dd3dc79c1c8c9aec/bin:/srv/slapgrid/slappart13/srv/testnode/dfa/shared/patch/c3ea1bad981ee188c62c20d5efd20941/bin:/srv/slapgrid/slappart13/srv/testnode/dfa/shared/perl/b09849d2f52498632d5aaa346847832f/bin:/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/pkgconfig/45eddb4001f77faec38bdaa6368a3cd7/bin:%(PATH)s\nLDFLAGS =-L/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/openssl/98cc177187bea94018e05faf2e5a3db8/lib -Wl,-rpath=/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/openssl/98cc177187bea94018e05faf2e5a3db8/lib -L/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/tcl/334718f5f980704ed69e7148da614924/lib -Wl,-rpath=/srv/slapgrid/slappart13/srv/testnode/dfa/inst/test0-0/tmp/shared/tcl/334718f5f980704ed69e7148da614924/lib -L/srv/slapgrid/slappart13/srv/testnode/dfa/shared/zlib/50f729c7869d762bd290da8443b3be99/lib -Wl,-rpath=/srv/slapgrid/slappart13/srv/testnode/dfa/shared/zlib/50f729c7869d762bd290da8443b3be99/lib -lm'
'make-target': 'check\ninstall'
'md5sum': '994b0aa879cbd95054048f34bf8ed954'
'patch-options': '-p1'
'recipe': 'slapos.recipe.cmmi'
'shared': 'true'
'url': 'http://apache.claz.org/trafficserver/trafficserver-9.1.0.tar.bz2'