wendelin.core: Fix test build 2
Always reference to in-tree eggs via ${<name>:egg} instead of just name. This fixes e.g. the following build failure:

    Installing wendelin.core-python.
    While:
      Installing wendelin.core-python.
      Base installation request: 'wendelin.core[test]', 'pygolang[pyx.build]', 'neoppod[tests]', 'ZEO[test]'
      Getting distribution for 'ZEO[test]'.
    Error: Picked: ZEO = 5.2.3

Not sure why it worked before.

Neoppod is a bit special - leave it as is for now.