v↑ tempstorage 2.12.2 -> 5.1 (today's latest)
tempstorage 2.12.2 is from 2012 and misses loadBefore fix which is
important when ERP5 is run with ZODB5 or ZODB4-wc2:

https://github.com/zopefoundation/tempstorage/commit/d187a86d

When that loadBefore fix is not there, the problem manifiests itself as
Zope not starting correctly with the following error in its log:

    2021-07-02 08:37:25,579 ERROR Zope.ZODBMountPoint Failed to mount database. <class 'ZODB.POSException.ReadConflictError'> (^@^@^@^@^@^@^@^@)
    Traceback (most recent call last):
     File ".../eggs/Zope2-2.13.30-py2.7.egg/Products/ZODBMountPoint/MountedObject.py", line 248, in _getOrOpenObject
       root = conn.root()
     File ".../parts/ZODB4-wc2/src/ZODB/Connection.py", line 405, in root
       return RootConvenience(self.get(z64))
     File ".../parts/ZODB4-wc2/src/ZODB/Connection.py", line 276, in get
       p, serial = self._load(oid)
     File ".../parts/ZODB4-wc2/src/ZODB/Connection.py", line 246, in _load
       return self._loadFrom(oid, self._storage)
     File ".../parts/ZODB4-wc2/src/ZODB/Connection.py", line 255, in _loadFrom
       raise ReadConflictError(oid)
    ReadConflictError: ^@^@^@^@^@^@^@^@

-> Fix it by upgrading tempstorage.

P.S. Note: tempstorage readme says that

	it is known to randomly lose data ...

https://github.com/zopefoundation/tempstorage/blob/5.1-2-gd131f5a/README.rst
https://github.com/zopefoundation/tempstorage/issues/8
https://github.com/zopefoundation/tempstorage/issues/12

/cc @tomo, @romain, @rafael