Move Matplotlib versions to slapos.cfg
Move the versions of matplotlib, matplotlib-inline and cycler pinned in
component/matplotlib/buildout.cfg to slapos.cfg.
The cycler version for Python 3.7 will be upgraded to 0.11.0 as it is
compatible.

One reason motivating this change is that the version of `cycler` in
stack/slapos.cfg is overriding the version specified in
component/matplotlib/buildout.cfg for the erp5-zope2 software release.
This is a problem because the former does not take into account the
Python version, while the later does.
Thus, attempting to compile erp5-zope2 would give the following error:

```
Getting distribution for 'cycler==0.11.0'.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Package 'cycler' requires a different Python: 2.7.18 not in '>=3.6'
While:
  Installing matplotlib.
  Base installation request: 'cycler', 'python-dateutil', 'numpy'
  Getting distribution for 'cycler==0.11.0'.
```

This adds the right version of `cycler` for Python 2 in `slapos.cfg`, so
that it does not fail.