slaprunner: skip non valid partition folder while backuping instance
Check if instance/slappartXX is a folder before backup it else import/export fail with this message:

    /srv/slapgrid/slappart18/bin/runner-exporter run at : Thu Oct  4 04:30:03 CEST 2018
    Traceback (most recent call last):
      File "<stdin>", line 17, in <module>
    OSError: [Errno 20] Not a directory: '/srv/slapgrid/slappart18/srv//runner/instance/slappart5-mariadb.dump.sql.gz'

In theory, instance/slappartXX should be SlapOS partition but user can create a file in instance folder and break
backup (see `/srv/slapgrid/slappart18/srv//runner/instance/slappart5-mariadb.dump.sql.gz`). So we skip non partition folder.