stack/wendelin: py3.13: Add support for spyne.
spyne is not really maintained upstream so import patches from Debian:
  * Update internal copy of six to support new import hooks. This fixes
    erp5_interfaces:testSOAPBinding failure:
      File "eggs/spyne-2.14.0-py3.13.egg/spyne/util/oset.py", line 3, in <module>
        from spyne.util.six.moves.collections_abc import MutableSet
      ImportError: Cannot load Component erp5.component.test.erp5_version.testSOAPBinding
  * cgi module got removed.