component/glibmm: add a patch for gcc 8 compatibility
Fix build errors on gcc 8:

   ../glibmm/threads.h: In member function 'GPrivate* Glib::Threads::Private<T>::gobj()':
   ../glibmm/threads.h:661:29: error: cannot convert 'GPrivate' {aka '_GPrivate'} to 'GPrivate*' {aka '_GPrivate*'} in return
      GPrivate* gobj() { return gobject_; }
                                ^~~~~~~~

This backport fixes from
https://github.com/GNOME/glibmm/commit/37d57ae9572b7d74aa385a30313eceae7f2d3fce
plus changes to generated files, as found in
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=85e6e0e04ae19670b071820947d941e521d1200e
or
https://src.fedoraproject.org/rpms/glibmm24/c/ecc4276486706c0ebc55aff3ac592499dc9df2a9?branch=master