theia: remove usless typeshed egg
This egg was not maintained and was removed from pypi
https://github.com/python/typeshed/issues/3001#issuecomment-592884362

I don't think we need it here, I probably added by mistake.

Interestingly when running this command it fails the first time with an
explicit error:

    Could not find a version that satisfies the requirement typeshed==0.0.1 (from -r /srv/slapgrid/slappart14/srv/testnode/cqc/inst/test0-0/tmp/soft/a6a44539f462e5e342cf8c714b7c8e5b/parts/python-language-server-requirements.txt (line 22)) (from versions: )
    No matching distribution found for typeshed==0.0.1 (from -r /srv/slapgrid/slappart14/srv/testnode/cqc/inst/test0-0/tmp/soft/a6a44539f462e5e342cf8c714b7c8e5b/parts/python-language-server-requirements.txt (line 22))

But when the command run again, another confusing error is displayed:

    Error: [Errno 13] Permission denied: '/srv/slapgrid/slappart14/srv/testnode/cqc/inst/test0-0/tmp/soft/a6a44539f462e5e342cf8c714b7c8e5b/parts/python-language-server/bin/activate.fish'