NEO: wait that the MySQL server is started before running tests
It already happened that the first tests of the suite failed
because the MySQL server was not fully started:

    OperationalError: (2002, 'Can\'t connect to local MySQL server through socket \'.../var/run/mariadb.sock\' (2 "No such file or directory")')