wendelin.core: Unbreak tests
After d8409763 (NEO: default ZODB was changed to 5) wendelin.core tests
started to fail to build because files, that the tests extend from, were
renamed on neoppod side. Example failure:

    An internal error occurred due to a bug in either zc.buildout or in a
    recipe being used:
    Traceback (most recent call last):
      File "/opt/slapos/eggs/zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 2359, in main
        user_defaults, command, args)
      File "/opt/slapos/eggs/zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 312, in __init__
        data['buildout'], override))
      File "/opt/slapos/eggs/zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 1974, in _open
        seen, processing))
      File "/opt/slapos/eggs/zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 1974, in _open
        seen, processing))
      File "/opt/slapos/eggs/zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 1974, in _open
        seen, processing))
      File "/opt/slapos/eggs/zc.buildout-2.7.1+slapos019-py3.7.egg/zc/buildout/buildout.py", line 1940, in _open
        with open(downloaded_filename) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/srv/slapgrid/slappart49/srv/project/slapos/software/neoppod/software-zodb5.cfg'

-> Fix it by adjusting wendelin.core tests correspondingly.

Similarly to 339490eb (components/zodbtools: reorganize test profiles)
make each test profile to explicitly indicate which configuration it
tests against.

Drop support for testing pristine ZODB4 - now only ZODB5 and ZODB4-wc2 remain.

We can drop test coverage for ZODB4 because slapos mainline switched to
ZODB5 to be used by default in 1c51c4cd (stack/erp5: version up all zope
stack (Zope 4.8.7), and because wendelin.core 2 works only with ZODB5
and ZODB4-wc2, but not with plain ZODB4.