monitor: use monitor- prefix in cert and key
By using a short filenames like "httpd.crt" or "httpd.key", we risk have
conflict with users of this stack. Use a name with more context, that
should likely not be used by applications.

This solves an issue with lamp stack, that was visible with nextcloud
software:

     While:
       Installing ca-apache-php.
     Error: The following paths are already installed by other sections: {'/srv/slapgrid/slappart8/srv/testnode/cvt/inst/test0-0/tmp/inst/ncs2/srv/ssl/certs/httpd.key': 'ca-monitor-httpd', '/srv/slapgrid/slappart8/srv/testnode/cvt/inst/test0-0/tmp/inst/ncs2/srv/ssl/certs/httpd.crt': 'ca-monitor-httpd'}