test: use monitoring_mixin from slapos.testing instead of slapos.test
importing slapos.test.monitoring_mixin doesn't always work because
slapos.toolbox also contains slapos.test but it is not a proper
namespace hence we have some tests failing with the following error:

ERROR: test (unittest.loader._FailedTest.test)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/srv/slapgrid/slappart51/srv/shared/python3/155d4b81b158312ef076eeec4b91ce29/lib/python3.11/unittest/loader.py", line 419, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/slapgrid/slappart51/srv/shared/python3/155d4b81b158312ef076eeec4b91ce29/lib/python3.11/unittest/loader.py", line 362, in _get_module_from_name
    __import__(name)
  File "/srv/slapgrid/slappart51/t/etm/soft/ec05e6d6f468d964fd71df824d8c7ed9/parts/slapos-repository/software/rapid-cdn/test/test.py", line 66, in <module>
    from slapos.test.monitoring_mixin import MonitoringPropagationTestMixin
ModuleNotFoundError: No module named 'slapos.test.monitoring_mixin'

Before fixing properly the namespace, we simply moved the
monitoring_mixin.py file in slapos.core/slapos/testing.

This is a followup of https://lab.nexedi.com/nexedi/slapos/-/merge_requests/1984

/reviewed-on https://lab.nexedi.com/nexedi/slapos/-/merge_requests/2064