erp5: Update tesseract to 3.04.01 because of compilation error.
Probably due to GCC6:
char_set.cpp:68:12: error: cannot convert 'bool' to 'tesseract::CharSet*' in return

Also update leptonica to 1.73 (>= 1.71 is required).