stack/slapos.cfg: lxml version up 4.9.1->5.2.1
only for python3

We now need to install lxml-clean-html separately, see the following
message:

  File "/srv/slapgrid/slappart71/srv/runner/software/e16145ec9280f63bd6c28ca2758d03f0/develop-eggs/lxml-5.2.1-py3.9-linux-x86_64.egg/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.