stack/slapos-py2.cfg: use pip 20.3.3
Pip introduced a new feature in https://github.com/pypa/pip/pull/9320 , which was backported to Pip 20.3.4. If the name after building the wheel does not conform with PEP 440 it shows a warning and returns None, causing an exception. This prevents to install SOAPpy version 0.12.0nxd001:

Installing eggs.
networkcache: Trying to download pypi:soappy=0.12.0nxd001 from network cache...
Getting distribution for 'SOAPpy==0.12.0nxd001'.
  WARNING: Built wheel for SOAPpy is invalid: Metadata 1.2 mandates PEP 440 version, but '0.12.0nxd001' is not
ERROR: Failed to build one or more wheels
While:
  Installing eggs.
  Base installation request: 'neoppod[admin, ctl, master]', 'cython-zstd', 'msgpack', 'mysqlclient', 'PyMySQL', 'yappi', 'ZODB', 'zodbtools', 'psutil', 'zope.testing', 'coverage', 'setproctitle', 'mock', 'Pympler', 'erp5_coverage_plugin', 'cryptography', 'caucase', 'wendelin.core', 'numpy', 'matplotlib', 'lxml', 'ocropy', 'pandas', 'Pillow', 'python-ldap', 'xmlsec', 'pysvn', 'pycrypto', 'scipy', 'scikit-learn', 'scikit-image', 'sympy', 'more-itertools', 'h5py', 'openpyxl', 'statsmodels', 'zbarlight', 'lock_file', 'astor', 'APacheDEX', 'PyStemmer', 'SOAPpy', 'chardet', 'collective.recipe.template', 'erp5diff', 'interval', 'ipdb', 'Jinja2', 'jsonschema', 'mechanize', 'oauthlib', 'objgraph', 'pynacl', 'bcrypt', 'paramiko', 'ply', 'pyflakes', 'PyPDF2', 'python-magic', 'python-memcached', 'pytz', 'requests', 'responses', 'urlnorm', 'uuid', 'xml_marshaller', 'xupdate_processor', 'feedparser', 'validictory', 'erp5.util', 'z3c.etestbrowser', 'huBarcode', 'qrcode', 'spyne', 'httplib2', 'suds', 'pprofile', 'pycountry', 'xfw', 'jsonschema', 'selenium', 'pytesseract', 'decorator', 'networkx', 'astroid', 'pylint', 'jedi', 'yapf', 'typing', 'pytracemalloc', 'xlrd', 'Zope2', 'tempstorage', 'Acquisition', 'ZEO', 'Products.PluggableAuthService', 'Products.PluginRegistry', 'Products.CMFActionIcons', 'Products.CMFCalendar', 'Products.CMFCore', 'Products.CMFDefault', 'Products.CMFTopic', 'Products.CMFUid', 'Products.DCWorkflow', 'Products.GenericSetup', 'five.localsitemanager', 'Products.MimetypesRegistry', 'Products.TIDStorage', 'Products.LongRequestLogger', 'zope.app.testing', 'StructuredText', 'polib', 'google-api-python-client', 'facebook-sdk', 'ipykernel', 'deepdiff', 'unidiff', 'zope.globalrequest', 'waitress', 'oic', 'strict-rfc3339', 'jsonschema[format]'
  Getting distribution for 'SOAPpy==0.12.0nxd001'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 2664, in main
    getattr(buildout, command)(args)
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 855, in install
    self._install_parts(install_args)
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1026, in _install_parts
    installed_files = self[part]._call(recipe.install)
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/buildout.py", line 1948, in _call
    return f()
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.recipe.egg-2.0.8.dev0+slapos009-py2.7.egg/zc/recipe/egg/egg.py", line 233, in install
    reqs, ws = self.working_set()
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.recipe.egg-2.0.8.dev0+slapos009-py2.7.egg/zc/recipe/egg/egg.py", line 113, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.recipe.egg-2.0.8.dev0+slapos009-py2.7.egg/zc/recipe/egg/egg.py", line 172, in _working_set
    patch_dict=patch_dict)
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/easy_install.py", line 1178, in install
    return installer.install(specs, working_set, patch_dict=patch_dict)
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/easy_install.py", line 835, in install
    for dist in self._get_dist(requirement, ws):
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/easy_install.py", line 711, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest, self)]
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/easy_install.py", line 2205, in _move_to_eggs_dir_and_compile
    [tmp_loc] = call_pip_wheel(dist.location, tmp_dest, options)
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/easy_install.py", line 2100, in call_pip_wheel
    call_pip_command(['wheel', '-w', dest], [spec], options)
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/zc.buildout-3.0.1+slapos009-py2.7.egg/zc/buildout/easy_install.py", line 2038, in call_pip_command
    subprocess.check_call(args, env=env)
  File "/srv/slapgrid/slappart42/t/eil/i/0/tmp/shared/python2.7/b678f8b70803e332acf256471a8a4ea8/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/srv/slapgrid/slappart42/t/eil/i/0/tmp/shared/python2.7/b678f8b70803e332acf256471a8a4ea8/bin/python2.7', '-m', 'pip', 'wheel', '-w', '/srv/slapgrid/slappart42/t/eil/i/0/tmp/soft/d2b846eaeed848c78d33488ff39faa2f/eggs/tmpjsp4EU', '--no-deps', '-q', '--no-index', '--no-build-isolation', '--no-python-version-warning', '--no-cache-dir', '/tmp/tmpAa7d3wget_dist/SOAPpy-0.12.0nxd001.tar.gz']' returned non-zero exit status 1