fixup! v↑ zodbtools (0.0.0.dev4)
9b5d8262 (v↑ zodbtools (0.0.0.dev4)) added zodburi and in turn ZEO
dependency to neoppod/software-common.cfg because zodburi currently
non-optionally requires ZEO.

However I forgot to notice that if we always pin ZEO to 4.x it will
require `transaction < 2` and this will break neoppod/software-zodb5.cfg
which requires ZODB 5.x and in turn `transaction >= 2`:

	Installing neoppod.
	Version and requirements information containing transaction:
	  [versions] constraint on transaction: 2.1.2
	  Requirement of ZODB==5.3.0: transaction>=2.0.3
	  Requirement of transaction>=2.0.3: zope.interface
	  Requirement of ZEO: transaction<2.0.0
	While:
	  Installing neoppod.
	Error: The requirement ('transaction<2.0.0') is not allowed by your [versions] constraint (2.1.2)

We already have ZODB = 4.x in software-common.cfg and software-zodb5.cfg
overrides it to ZODB = 5.x, but ZEO was left not-overwritten and this
way there becomes conflicting requirement on transaction.

Fix it by also overriding ZEO in software-zodb5.cfg

/reported-and-reviewed-by @jm
/reported-on https://lab.nexedi.com/nexedi/slapos/merge_requests/242#note_49754