stack/erp5: depends on Products.TemporaryFolder
Prevents error like this in the log for ZODB with a tmep_folder

2024-10-04 14:14:53,288 ERROR Zope.ZODBMountPoint Failed to mount database. <type 'exceptions.ImportError'> (No module named TemporaryFolder)
Traceback (most recent call last):
  File "./eggs/Products.ZODBMountPoint-1.3-py2.7.egg/Products/ZODBMountPoint/MountedObject.py", line 255, in _getOrOpenObject
    obj = self._traverseToMountedRoot(root, parent)
  File "./eggs/Products.ZODBMountPoint-1.3-py2.7.egg/Products/ZODBMountPoint/MountedObject.py", line 213, in _traverseToMountedRoot
    obj = blazer.traverseOrConstruct(real_path)
  File "./eggs/Products.ZODBMountPoint-1.3-py2.7.egg/Products/ZODBMountPoint/MountedObject.py", line 81, in traverseOrConstruct
    container = self._construct(container, part)
  File "./eggs/Products.ZODBMountPoint-1.3-py2.7.egg/Products/ZODBMountPoint/MountedObject.py", line 108, in _construct
    klass = jar.db().classFactory(jar, self.module_name, self.class_name)
  File "./eggs/Zope-4.8.7-py2.7.egg/Zope2/Startup/datatypes.py", line 288, in simpleClassFactory
    m = __import__(module, _globals, _globals, _silly)
ImportError: No module named TemporaryFolder