Revert "rapid-cdn: Relax promise constraint"
This reverts commit b6f08b9ec0691c2e22ea270fc1212224172eef24.

Because this promise is relaxed, it leads to situation, that slaves are not
prepared, and no more processing would be needed.

Most possibly much more advanced logic is required.

This revertion is created to store the finding.

The error is like:

======================================================================
FAIL: test_https_url (test.TestSlave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/slapgrid/slappart33/t/dwd/soft/5dab459bdda9e53f1db7e0d954b37126/parts/slapos-repository/software/rapid-cdn/test/test.py", line 4792, in test_https_url
    self.assertEqual(
AssertionError: b'---[25 chars]nMIIDKjCCAhKgAwIBAgIUXLVeJJwHEQDnyJAbiqOlk7qkN[1100 chars]--\n' != b'---[25 chars]nMIIDVzCCAj+gAwIBAgIUJ99OAJ5qFcT5shJYBLHmdHKFu[1162 chars]--\n't