stack/{slapos.cfg,caucase}: Version up.
To fix caucased failures:
  File "caucase/caucase/http.py", line 799, in main
    http_cas=http_cas,
  File "caucase/caucase/http.py", line 397, in getSSLContext
    http_cas.createCertificate(csr_id)
  File "caucase/caucase/ca.py", line 281, in createCertificate
    template_csr=template_csr,
  File "caucase/caucase/ca.py", line 328, in _createCertificate
    x509.SubjectKeyIdentifier,
  File "cryptography-2.3.1-py2.7-linux-x86_64.egg/cryptography/x509/extensions.py", line 189, in from_issuer_subject_key_identifier
    key_identifier=ski.value.digest,
AttributeError: 'SubjectKeyIdentifier' object has no attribute 'value'

In turn, this requires updating cryptography dependencies.
In turn, this requires updating requests as our old version is
incompatible with current idna version.
In turn, this requires updating requests dependencies.
And finally, this allows/requires updating some pins in SRs:
- software/jupyter: Version up certifi.
- stack/erp5: Un-pin chardet, as it is already pinned at stack/slapos level.