fixup! NEO: add support for SQLite backend
We no enforce formatting of json schema, this was causing a test
failure:
```

======================================================================
FAIL: test_schema_neoppod_instance_neo_input_schema_json_format (slapos.test.test_json_schema.TestJSONSchemaValidation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/slapgrid/slappart0/srv/testnode/bpy/inst/test0-0/parts/slapos.cookbook/slapos/test/test_json_schema.py", line 80, in run
    content.splitlines())
AssertionError: Lists differ: ['{', '  "$schema": "http://js... != ['{', '  "$schema": "http://js...

First differing element 87:
'            "description": "Storage type. Defaults to MySQL if available, else SQLite.",'
'              "description": "Storage type. Defaults to MySQL if available, else SQLite.",'

First list contains 3 additional elements.
First extra element 119:
'  },'

Diff is 5422 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
```

/reviewed-on https://lab.nexedi.com/nexedi/slapos/merge_requests/482