component/postfix: update to 3.7.2
Fixes build on recent libc headers:
set -e; for i in src/util src/global src/dns src/tls src/xsasl src/master src/milter src/postfix src/fsstone src/smtpstone src/sendmail src/error src/pickup src/cleanup src/smtpd src/local src/trivial-rewrite src/qmgr src/oqmgr src/smtp src/bounce src/pipe src/showq src/postalias src/postcat src/postconf src/postdrop src/postkick src/postlock src/postlog src/postmap src/postqueue src/postsuper src/qmqpd src/spawn src/flush src/verify src/virtual src/proxymap src/anvil src/scache src/discard src/tlsmgr src/postmulti src/postscreen src/dnsblog src/tlsproxy src/posttls-finger src/postlogd; do \
 (set -e; echo "[$i]"; cd $i; make 'WARN=-Wmissing-prototypes -Wformat -Wno-comment -fcommon' update MAKELEVEL=) || exit 1; \
done
[src/util]
gcc -I. -I../../include -DUSE_SASL_AUTH -DUSE_CYRUS_SASL -DUSE_TLS -DHAS_PCRE -DHAS_DB -I/home/vifib/software/b3708eca6720657934c5dee0b8247042/parts/libdb/include -I/home/vifib/software/b3708eca6720657934c5dee0b8247042/parts/pcre/include -I/home/vifib/software/b3708eca6720657934c5dee0b8247042/parts/openssl/include -I/home/vifib/software/b3708eca6720657934c5dee0b8247042/parts/cyrus-sasl/include/sasl -I/home/vifib/software/b3708eca6720657934c5dee0b8247042/parts/libnsl/include -DNO_EAI -DHAS_DEV_URANDOM -UUSE_DYNAMIC_LIBS -DDEF_SHLIB_DIR=\"no\" -UUSE_DYNAMIC_MAPS -Wmissing-prototypes -Wformat -Wno-comment -fcommon  -g -O -I. -DLINUX5 -c attr_clnt.c
In file included from attr_clnt.c:87:
./sys_defs.h:763: warning: "HAS_DB" redefined
  763 | #define HAS_DB
      |
<command-line>: note: this is the location of the previous definition
In file included from attr_clnt.c:88:
/usr/include/unistd.h:363:13: error: conflicting types for 'closefrom'; have 'void(int)'
  363 | extern void closefrom (int __lowfd) __THROW;
      |             ^~~~~~~~~
./sys_defs.h:1512:12: note: previous declaration of 'closefrom' with type 'int(int)'
 1512 | extern int closefrom(int);
      |            ^~~~~~~~~
make: *** [Makefile:192: attr_clnt.o] Error 1
make: *** [Makefile:94: update] Error 1

Also, switch from Wietse's own source ftp to a mirror.