Fix error compiling Inkscape due to older GCC.
When using older GCC versions (e.g. 8.3.0), Inkscape fails with an error
similar to:

```C++
/srv/slapgrid/slappart15/srv/runner/instance/slappart7/tmp/shared/inkscape/31c6ae5c72c5325d479cca38e62b82bb/.build/inkscape-1.3.2_2023-11-25_091e20ef0f/src/ui/tools/booleans-subitems.cpp: In lambda function:
/srv/slapgrid/slappart15/srv/runner/instance/slappart7/tmp/shared/inkscape/31c6ae5c72c5325d479cca38e62b82bb/.build/inkscape-1.3.2_2023-11-25_091e20ef0f/src/ui/tools/booleans-subitems.cpp:213:61: error: cannot deduce template arguments for ‘uniform_real_distribution’ from ()
     auto ranf = [&] { return std::uniform_real_distribution()(gen); };
```

This may be an instance of this problem:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81486

In any case, setting a minimum version of 10.5 for GCC when building
Inkscape, as done in this commit, seems to fix this.

See merge request nexedi/slapos!1634