component/fluentd: fix failing install pinning gems version
- pins component/fluentd gems version to fix :

  ERROR:  Error installing fluentd:
	msgpack requires Ruby version >= 2.4.

  encountered while supplying software/fluentd in a SlapOS Webrunner.

- removes outdated gem arguments '--no-ri --no-rdoc'
  by default `rubygemsrecipe` uses '--no-document' (see https://lab.nexedi.com/nexedi/rubygemsrecipe/blob/master/rubygems.py#L206)

- splits `gem-options` arguments to fit the README example (see https://lab.nexedi.com/nexedi/rubygemsrecipe/blob/master/README.rst#L50)

- adds minimal test to check fluentd SR instanciation