software/grafana: revert to "traditional" promises
Monitoring promise break instanciation:
  UserError: No section named 'monitor-base-promise'

and telegraf startup script is using influxdb promise, because it has a
bug that it needs to start only after influxdb is available, so it does
not look so easy to switch to monitoring stack.

Also, this software is experimental (and also is conceptually a
monitoring software on its own), so it does not need monitoring for now.

This reverts commit 48b6c27c1c95abc9a12205259e4e3f785d6e2b22.